depth_camera:
  to_meters: 0.001 # divide pixel value by 1000 to get meters
  rate: 1
  fov: # in degrees
    x: 89.57
    y: 59.24
  size: # number of pixels in the image
    x: 6
    y: 4
  range_min: 0.0
  range_max: 8.0
  trimmed_range_max: 7.0
  offset:
    x: 0.210546
    y: -0.0630657
    z: -0.0984911
    roll: -1.6574
    pitch: 0.0
    yaw: -1.6039
  noise:
    sigma: 0.01
map:
  width: 100
  height: 100
  depth: 50
  origin: [-35,-35,-2]
  resolution: 1.0
  hit_probability: 0.99
  miss_probability: 0.1
  free_threshold: 0.3
  occupied_threshold: 0.7
  min_clamp: 0.01
  max_clamp: 0.9999
